### ISSUE TITLE
No message?

### ISSUE THREAD

**Issue by sonwa** [aellwein/coap#5]
hi,I can't receive the content with the "AT+M2MCLISEND" command, but I can receive the message with "AT+ M2MCLINEW". Why?

**Comment by aellwein** [comment]
Hi,
can you be more descriptive what you mean with "AT+..."? 
It's surely not inside the RFC 7252 CoAP specification.
In current state, the framework is only able to receive messages and respond to them (without retries),
the progressive sending is not implemented yet. But you can "simulate" a LwM2M server, i.e. respond to a POST on /rd resource, like in [server.go](https://github.com/aellwein/coap/blob/develop/_examples/server.go) example

**Comment by sonwa** [comment]
![image](https://user-images.githubusercontent.com/1425134/48117616-bbea2b80-e2a4-11e8-8ef4-651fe344aba4.png)

Yes, it should be sending this."simulate" server

**Comment by aellwein** [comment]
The behavior of the example server is all correct, if it is sent a GET on unknown resource (in your case 5770/t/d), it responds with 4.04 Not Found. Tested with current version:
![image](https://user-images.githubusercontent.com/3179781/48220566-f67cc280-e38f-11e8-8a0e-cabe8ccc78e9.png)

In order to respond appropriately, you need to register the resource properly in the server. Hence closing this issue as invalid.
